---

- name: Install elrepo for kernel upgrade
  rpm_key:
    state: present
    key: https://www.elrepo.org/RPM-GPG-KEY-elrepo.org

- name: Add plex repo
  yum_repository:
    name: Plex
    baseurl: https://downloads.plex.tv/repo/rpm/$basearch/
    gpgkey: https://downloads.plex.tv/plex-keys/PlexSign.key
    description: Plex
    enabled: yes
    gpgcheck: yes

- name: Adding ffmpeg and kernel deps
  dnf:
    name: "{{ item.name }}"
    enablerepo: "{{ item.repo }}"
    disable_gpg_check: "{{ item.gpg_check }}"
  with_items: 
    - "{{ repo_enabled }}"

- name: Install packages
  dnf:
    name: "{{ packages }}"
    state: present

- name: Upgrade pip
  pip:
    name: pip
   