---

- name: Configuring sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - { name: "net.ipv4.conf.all.forwarding", value: 0 }
    - { name: "net.core.somaxconn", value: 4096 }
    - { name: "net.ipv4.tcp_fin_timeout", value: 30 }
    - { name: "net.ipv4.tcp_keepalive_intvl", value: 30 }
    - { name: "net.ipv4.tcp_keepalive_time", value: 120 }
    - { name: "net.ipv4.tcp_max_syn_backlog", value: 4096 }
    - { name: "vm.swappiness", value: 1 }
    - { name: "vm.dirty_background_ratio", value: 10 }
    - { name: "vm.dirty_ratio", value: 20 }
    - { name: "net.core.rmem_default", value: 262144 }
    - { name: "net.core.wmem_default", value: 262144 }
    - { name: "net.core.rmem_max", value: 262144 }
    - { name: "net.core.wmem_max", value: 262144 }
    - { name: "net.ipv6.conf.all.disable_ipv6", value: 1 }

- name: Disable THP
  blockinfile:
    path: /etc/rc.local
    state: present
    create: yes
    block: |
      if test -f /sys/kernel/mm/transparent_hugepage/enabled; then
        echo never > /sys/kernel/mm/transparent_hugepage/enabled
      fi

- name: Setup static ifcg
  template:
    src: ifcfg-eno1.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}
    owner: root
    group: root
    mode: '0644'
    backup: yes
  register: result