---

- name: Configuring sysctl
  sysctl:
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - "{{ kernel_mods }}"

- name: Disable THP
  blockinfile:
    path: /etc/rc.local
    state: present
    create: yes
    block: |
      if test -f /sys/kernel/mm/transparent_hugepage/enabled; then
        echo never > /sys/kernel/mm/transparent_hugepage/enabled
      fi

- name: Setup static ifcg
  template:
    src: ifcfg-eno1.j2
    dest: /etc/sysconfig/network-scripts/ifcfg-{{ ansible_default_ipv4.interface }}
    owner: root
    group: root
    mode: '0644'
    backup: yes
  register: result

- name: Copy nginx template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    backup: yes
